// constants auth
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';
export const SET_HIDDEN_LIST = 'SET_HIDDEN_LIST';
export const ADD_HIDDEN_ITEM = 'ADD_HIDDEN_ITEM';
export const SET_AUTHENTICATE = 'SET_AUTHENTICATE';
export const SET_LOADING = 'SET_LOADING';
export const SET_SOCKET_STATE = 'SET_SOCKET_STATE';
// constants ui
export const SET_USER_TARGET_INFO = 'SET_USER_TARGET_INFO';
export const CHANGE_VOLUME_STATE = 'CHANGE_VOLUME_STATE';
export const CHANGE_MIC_STATE = 'CHANGE_MIC_STATE';
export const SET_OPEN_ADD_GROUP = 'SET_OPEN_ADD_GROUP';
export const SET_USER_STATE = 'SET_USER_STATE';
export const SET_OPEN_ALERT = 'SET_OPEN_ALERT';
export const SET_MESSAGE_ALERT = 'SET_MESSAGE_ALERT';
// constants group
export const SET_GROUPS = 'SET_GROUPS';
export const SET_SELECT_GROUP = 'SET_SELECT_GROUP';
export const ADD_GROUP = 'ADD_GROUP';
export const SET_CHANNELS = 'SET_CHANNELS';
// constants socket
export const SET_MAIN_SOCKET = 'SET_MAIN_SOCKET';
// constants socketVoice
export const SET_VOICE_CHANNEL_ID = 'SET_VOICE_CHANNEL_ID';
export const SET_VOICE_SOCKET = 'SET_VOICE_SOCKET';
export const SET_PEER = 'SET_PEER';
export const SET_STREAMING = 'SET_STREAMING';
export const SET_STREAMINGS = 'SET_STREAMINGS';
export const ADD_STREAMING = 'ADD_STREAMING';
// constants message
export const SET_DIRECT_MESSAGES = 'SET_DIRECT_MESSAGES';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const UPDATE_DIRECT_MESSAGE = 'UPDATE_DIRECT_MESSAGE';
export const SET_MESSAGES = 'SET_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_INPUT_SEARCH_MESSAGE = 'SET_INPUT_SEARCH_MESSAGE';
//call
export const SET_OPEN_NEW_CALL = 'SET_OPEN_NEW_CALL';
export const SET_USER_NEW_CALL = 'SET_USER_NEW_CALL';
export const SET_STATE_CALL = 'SET_STATE_CALL';
export const SET_OPEN_INCOMING_CALL = 'SET_OPEN_INCOMING_CALL';
export const SET_USER_INCOMING_CALL = 'SET_USER_INCOMING_CALL';
export const SET_SIGNAL_INCOMING_CALL = 'SET_SIGNAL_INCOMING_CALL';
export const SET_USER_VIDEO_ONE = 'SET_USER_VIDEO_ONE';
export const SET_USER_VIDEO_TWO = 'SET_USER_VIDEO_TWO';
export const SET_PEER_CALL = 'SET_PEER_CALL';
